# Generated by Django 5.1.3 on 2024-11-20 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpublisher',
            old_name='comapny_Name',
            new_name='company_Name',
        ),
        migrations.AddField(
            model_name='addpublisher',
            name='publisher_photo',
            field=models.FileField(default=django.utils.timezone.now, max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
