# Generated by Django 5.1.3 on 2024-11-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_adminlog_alter_addpublisher_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='addBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('authors_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('published_date', models.CharField(max_length=200)),
                ('book_photo', models.FileField(max_length=200, upload_to='')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
