# Generated by Django 5.1.3 on 2024-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_addbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
