# Generated by Django 5.1.3 on 2024-11-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_addbook_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='addReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('authors_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('published_date', models.CharField(max_length=200)),
                ('review', models.FileField(max_length=200, upload_to='')),
            ],
        ),
    ]
