# Generated by Django 5.1.3 on 2024-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_addreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtoLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_ID', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
