# Generated by Django 5.1.3 on 2024-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_addtolibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtolibrary',
            name='photo',
            field=models.FileField(default='no image', max_length=500, upload_to=''),
        ),
    ]
