# Generated by Django 5.1.3 on 2024-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_addtolibrary_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtolibrary',
            name='author_name',
            field=models.CharField(default='nil', max_length=200),
        ),
    ]
