# Generated by Django 5.1.3 on 2024-11-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_addtolibrary_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreview',
            name='published_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addreview',
            name='review',
            field=models.CharField(max_length=2000),
        ),
    ]
