# Generated by Django 5.1.3 on 2024-11-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_alter_addreview_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtolibrary',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='bookapp.addreview'),
        ),
    ]
