# Generated by Django 5.1.3 on 2024-11-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_addreview_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_books', to='bookapp.addbook'),
        ),
    ]
