# Generated by Django 5.1.3 on 2024-11-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_alter_addreview_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addreview',
            name='book',
        ),
    ]
