# Generated by Django 5.1.3 on 2024-11-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_addreview_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_books',
                                    to='bookapp.addbook'),

            # field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
            # related_name='all_books', to='bookapp.addbook'),
            preserve_default=False,
        ),
    ]
