# Generated by Django 5.1.3 on 2024-11-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0020_alter_addreview_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreview',
            name='rating',
            field=models.IntegerField(),

            # field=models.IntegerField(default=0),
        ),
    ]
