# Generated by Django 5.1.3 on 2024-11-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0022_alter_addreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreview',
            name='rating',
            field=models.IntegerField(),
            # field=models.IntegerField(blank=True, null=True),
        ),
    ]
