# Generated by Django 5.1.3 on 2024-11-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0024_alter_addreview_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='addtolibrary',
            name='review',
        ),
        migrations.DeleteModel(
            name='addBook',
        ),
        migrations.DeleteModel(
            name='addReview',
        ),
        migrations.DeleteModel(
            name='addtoLibrary',
        ),
    ]
