# Generated by Django 5.1.3 on 2024-11-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0025_remove_addreview_book_remove_addtolibrary_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='addBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('authors_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('published_date', models.CharField(max_length=200)),
                ('book_photo', models.FileField(max_length=200, upload_to='')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='addReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('authors_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('published_date', models.DateField()),
                ('review', models.CharField(max_length=2000)),
                ('book', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_books', to='bookapp.addbook')),
            ],
        ),
        migrations.CreateModel(
            name='addtoLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_ID', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(default='nil', max_length=200)),
                ('photo', models.FileField(default='no image', max_length=500, upload_to='')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='bookapp.addreview')),
            ],
        ),
    ]
