# Generated by Django 5.1.3 on 2024-12-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0029_remove_addreview_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='user_photo',
            field=models.FileField(default='no photo', max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='addpublisher',
            name='company_Name',
            field=models.CharField(max_length=200),
        ),
    ]
