# Generated by Django 5.1.3 on 2024-12-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0030_adduser_user_photo_alter_addpublisher_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='user_photo',
            field=models.FileField(blank=True, default='no photo', null=True, upload_to='media/'),
        ),
    ]
