# Generated by Django 5.1.3 on 2024-12-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0031_alter_adduser_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreview',
            name='published_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='user_photo',
            field=models.FileField(default='no photo', max_length=200, upload_to=''),
        ),
    ]
