# Generated by Django 5.1.3 on 2024-12-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0032_alter_addreview_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreview',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
