# Generated by Django 5.1.3 on 2024-12-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0033_alter_addreview_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='copyrightapplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Name', models.CharField(max_length=200)),
                ('book_Id', models.IntegerField()),
                ('published_Date', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_Number', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=1000)),
                ('declaration', models.CharField(max_length=200)),
                ('signature', models.FileField(max_length=200, upload_to='')),
                ('document', models.FileField(max_length=200, upload_to='')),
            ],
        ),
    ]
