# Generated by Django 5.1.3 on 2024-12-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0034_copyrightapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightapplied',
            name='published_Name',
            field=models.CharField(default='not set', max_length=200),
        ),
    ]
