# Generated by Django 5.1.3 on 2024-12-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0035_copyrightapplied_published_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightapplied',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
