# Generated by Django 5.1.3 on 2024-12-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0036_copyrightapplied_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreview',
            name='bookId',
            field=models.IntegerField(default=None),
        ),
    ]
