# Generated by Django 5.1.3 on 2024-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0037_addreview_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtolibrary',
            name='book_ID',
            field=models.IntegerField(default=None),
        ),
    ]
